function (target_require_standard target standard)
  if (${CMAKE_VERSION} VERSION_GREATER 3.1)
    if ("${standard}" STREQUAL "c11")
      set_property (TARGET ${target} PROPERTY C_STANDARD "11")
    elseif ("${standard}" STREQUAL "c99")
      set_property (TARGET ${target} PROPERTY C_STANDARD "99")
    elseif ("${standard}" STREQUAL "c90")
      set_property (TARGET ${target} PROPERTY C_STANDARD "90")
    elseif ("${standard}" STREQUAL "c89")
      set_property (TARGET ${target} PROPERTY C_STANDARD "90")
    elseif ("${standard}" STREQUAL "c++14")
      set_property (TARGET ${target} PROPERTY CXX_STANDARD "14")
    elseif ("${standard}" STREQUAL "c++11")
      set_property (TARGET ${target} PROPERTY CXX_STANDARD "11")
    elseif ("${standard}" STREQUAL "c++98")
      set_property (TARGET ${target} PROPERTY CXX_STANDARD "98")
    else ()
      message (FATAL_ERROR "Unknown standard: ${standard} (valid: c11, c99, c90, c89, c++14, c++11, c++98)")
    endif ()

    if ("${standard}" MATCHES "^c\\+\\+")
      set_property (TARGET ${target} PROPERTY CXX_STANDARD_REQUIRED TRUE)
    else ()
      set_property (TARGET ${target} PROPERTY C_STANDARD_REQUIRED TRUE)
    endif ()
  else ()
    # TODO: make this portable
    set_property (TARGET COMPILE_FLAGS APPEND_STRING "-std=${standard}")
  endif ()
endfunction ()
